
report = new com.openbravo.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Rate");
report.setReport("/dev/itechsolutions/reports/rate");
report.setResourceBundle("dev/itechsolutions/reports/rate_messages");

report.setSentence("SELECT"
                     + " cr.datefrom"
                     + ", cr.rate"
                     + ", CONCAT(c.iso_code, ' - ', c.name) currency"
                  + " FROM currencyRate cr"
                  + " INNER JOIN currency c ON c.id = cr.currencyId"
                  + " ORDER BY cr.datefrom DESC, cr.currencyId ");

report.addField("datefrom", com.openbravo.data.loader.Datas.TIMESTAMP);
report.addField("rate", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("currency", com.openbravo.data.loader.Datas.STRING);

report;