/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.itechsolutions.pos.currency;

import com.openbravo.pos.forms.AppLocal;
import com.openbravo.basic.BasicException;
import com.openbravo.data.user.DirtyManager;
import com.openbravo.data.user.EditorRecord;
import com.openbravo.format.Formats;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryException;
import java.awt.Component;
import java.util.UUID;

/**
 *
 * @author Argenis Rodríguez
 */
public class CurrencyView extends javax.swing.JPanel implements EditorRecord {
    
    private Object m_oId;
    
    private AppView appView;
    private DirtyManager m_dirty;
    
    public CurrencyView(AppView app, DirtyManager dirty) {
        
        try {
            appView = app;
            
            initComponents();
            
            m_dirty = dirty;
            
            jISOCodeText.getDocument().addDocumentListener(dirty);
            jNameText.getDocument().addDocumentListener(dirty);
            
            init();
        } catch (BeanFactoryException e) {
        }
    }
    
    private void init() {
        writeValueEOF();
    }
    
    /**
     * Creates new form CurrencyView
     */
    public CurrencyView() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNameLabel = new javax.swing.JLabel();
        jNameText = new javax.swing.JTextField();
        jISOCodeLabel = new javax.swing.JLabel();
        jISOCodeText = new javax.swing.JTextField();

        jNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jNameLabel.setText(AppLocal.getIntString("label.currency.name")); // NOI18N

        jNameText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jNameText.setToolTipText("");
        jNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTextActionPerformed(evt);
            }
        });

        jISOCodeLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jISOCodeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/info.png"))); // NOI18N
        jISOCodeLabel.setText(AppLocal.getIntString("label.currency.isocode")); // NOI18N

        jISOCodeText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jISOCodeText.setToolTipText("");
        jISOCodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jISOCodeTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jISOCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jISOCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNameText)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jISOCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jISOCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTextActionPerformed
        
    }//GEN-LAST:event_jNameTextActionPerformed

    private void jISOCodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jISOCodeTextActionPerformed
        
    }//GEN-LAST:event_jISOCodeTextActionPerformed
    
    @Override
    public void writeValueEOF() {
        m_oId = null;
        jISOCodeText.setText(null);
        jNameText.setText(null);
    }
    
    @Override
    public void writeValueInsert() {
        m_oId = null;
        jISOCodeText.setText(null);
        jNameText.setText(null);
        
        repaint();
        refresh();
    }
    
    @Override
    public void writeValueEdit(Object value) {
        Object[] currency = (Object[]) value;
        
        m_oId = currency[0];
        jNameText.setText(Formats.STRING.formatValue(currency[1]));
        jISOCodeText.setText(Formats.STRING.formatValue(currency[2]));
        
        repaint();
        refresh();
    }
    
    @Override
    public void writeValueDelete(Object value) {
        Object[] currency = (Object[]) value;
        
        m_oId = currency[0];
        
        jNameText.setText(Formats.STRING.formatValue(currency[1]));
        jISOCodeText.setText(Formats.STRING.formatValue(currency[2]));
        
        repaint();
        refresh();
    }
    
    @Override
    public void refresh() {
        
    }
    
    @Override
    public Component getComponent() {
        return this;
    }
    
    @Override
    public Object createValue() throws BasicException {
        Object[] currency = new Object[3];
        
        currency[0] = m_oId == null ? UUID.randomUUID().toString() : m_oId;
        currency[1] = Formats.STRING.parseValue(jNameText.getText());
        currency[2] = Formats.STRING.parseValue(jISOCodeText.getText());
        
        return currency;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jISOCodeLabel;
    private javax.swing.JTextField jISOCodeText;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jNameText;
    // End of variables declaration//GEN-END:variables
}
